M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 17, Wednesday 19:00:29
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-05-17T19:00:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.850
%
G90
G05
T1
X50292Y-56266
X50292Y-60066
T2
X28160Y-58425
X28160Y-106685
T0
M30
